name: deploy-infra

on:
  push:
    branches: [main]
    paths: ["infra/**", ".github/workflows/deploy.yml"]

jobs:
  terraform:
    # Grant the workflow ability to dispatch another workflow
    permissions: {id-token: write, contents: read, actions: write}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: cicd-gh-actions@indianstall10n.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        working-directory: ./infra
        env:
          TF_VAR_api_user: ${{ secrets.RACING_API_USER }}
          TF_VAR_api_pass: ${{ secrets.RACING_API_PASS }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Trigger nightly-status workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: nightly-status
