name: nightly-status
on:
  workflow_dispatch:        # manual run button
  schedule:
    - cron: "0 09 * * *"    # 09:00 UTC (04:00 CT) daily

jobs:
  gather:
    permissions: {id-token: write, contents: write}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: cicd-gh-actions@indianstall10n.iam.gserviceaccount.com

      - name: Collect live status
        run: |
          gcloud config set project indianstall10n
          mkdir -p status
          gcloud functions list      --format=json > status/functions.json
          gcloud run services list   --format=json > status/run.json
          gcloud dataflow jobs list --region=us-central1 --statuses=active,done \
                --format=json > status/dataflow.json
          gcloud ai custom-jobs list --format=json > status/ai.json
          gcloud monitoring metrics read \
                'compute.googleapis.com/instance/cpu/utilization' \
                --limit=1 --format=json > status/metrics.json
          jq -n '{
            generated: now|todate,
            functions:  input,
            run:        input,
            dataflow:   input,
            ai:         input,
            metrics:    input
          }' status/functions.json status/run.json status/dataflow.json status/ai.json status/metrics.json \
            > status.json

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./status
          destination_dir: .
