      - name: Collect live status
        run: |
          gcloud config set project indianstall10n
          mkdir -p status

          gcloud functions list        --format=json > status/functions.json
          gcloud run services list     --format=json > status/run.json
          gcloud dataflow jobs list    --region=us-central1 \
                --format=json > status/dataflow.json
          gcloud ai custom-jobs list   --region=us-central1 \
                --format=json > status/ai.json
          gcloud monitoring metrics read \
                'compute.googleapis.com/instance/cpu/utilization' \
                --limit=1 --format=json > status/metrics.json

          jq -n '{
            generated: now|todate,
            functions:  input,
            run:        input,
            dataflow:   input,
            ai:         input,
            metrics:    input
          }' status/functions.json status/run.json status/dataflow.json \
             status/ai.json status/metrics.json > status.json
